"""pjkit — pure logic for the pj periodic-job framework.

No I/O, no launchctl, no filesystem mutation lives here so it can be unit
tested in isolation. The pj CLI imports this module.
"""

import plistlib
import re
import shlex
import tomllib
from collections import namedtuple
from pathlib import Path

LABEL_PREFIX = "com.dimitrov.pj"

_PLIST_COMMENT = (
    "<!-- generated by pj — edit job.toml then `pj apply`; "
    "manual edits here are overwritten on apply -->"
)

JobPaths = namedtuple("JobPaths", "dir toml wrapper plist log_out log_err")

# launchd Weekday numbering: Sunday is 0 (7 also works), Monday..Saturday 1..6.
_WEEKDAYS = {
    "sun": 0,
    "mon": 1,
    "tue": 2,
    "wed": 3,
    "thu": 4,
    "fri": 5,
    "sat": 6,
}

_NAME_RE = re.compile(r"^[a-z0-9][a-z0-9_-]*$")


class JobSpecError(ValueError):
    """Raised when user-supplied job specification is invalid."""


def parse_time(value):
    """'HH:MM' -> (hour, minute). Raises JobSpecError on anything invalid."""
    text = value.strip()
    if ":" not in text:
        raise JobSpecError(f"time must be HH:MM, got {value!r}")
    hh, _, mm = text.partition(":")
    try:
        hour, minute = int(hh), int(mm)
    except ValueError:
        raise JobSpecError(f"time must be HH:MM with numbers, got {value!r}")
    if not (0 <= hour <= 23):
        raise JobSpecError(f"hour must be 0-23, got {hour}")
    if not (0 <= minute <= 59):
        raise JobSpecError(f"minute must be 0-59, got {minute}")
    return hour, minute


def parse_every(value):
    """'30m' / '2h' / '90s' -> seconds (int > 0). Raises JobSpecError."""
    text = value.strip().lower()
    match = re.fullmatch(r"(\d+)([smh])", text)
    if not match:
        raise JobSpecError(f"interval must be like 30m, 2h, 90s; got {value!r}")
    amount = int(match.group(1))
    unit_seconds = {"s": 1, "m": 60, "h": 3600}[match.group(2)]
    seconds = amount * unit_seconds
    if seconds <= 0:
        raise JobSpecError(f"interval must be greater than zero, got {value!r}")
    return seconds


def parse_days(value):
    """'mon,wed,fri' -> sorted, de-duped launchd weekday ints. Raises JobSpecError."""
    result = set()
    for token in value.split(","):
        name = token.strip().lower()
        if not name:
            continue
        if name not in _WEEKDAYS:
            raise JobSpecError(
                f"unknown day {token.strip()!r}; use {', '.join(_WEEKDAYS)}"
            )
        result.add(_WEEKDAYS[name])
    if not result:
        raise JobSpecError(f"no days given in {value!r}")
    return sorted(result)


def validate_name(name):
    """Job name usable as a launchd label, dir, and filename. Raises JobSpecError."""
    if not _NAME_RE.match(name or ""):
        raise JobSpecError(
            f"name must be lowercase letters/digits/-/_ and start alnum, got {name!r}"
        )
    return name


def schedule_to_launchd(schedule):
    """Translate a manifest schedule dict into launchd plist keys.

    calendar -> StartCalendarInterval (single dict, or list when there are
    multiple time/weekday entries); interval -> StartInterval seconds.
    RunAtLoad is added when requested. Raises JobSpecError on bad specs.
    """
    keys = {}
    if schedule.get("run_at_load"):
        keys["RunAtLoad"] = True

    kind = schedule.get("kind")
    if kind == "interval":
        keys["StartInterval"] = parse_every(schedule["every"])
        return keys

    if kind == "calendar":
        times = schedule.get("times") or []
        if not times:
            raise JobSpecError("calendar schedule needs at least one time")
        time_tuples = [parse_time(t) for t in times]
        days = schedule.get("days") or []
        day_ints = parse_days(",".join(days)) if days else []

        entries = []
        if day_ints:
            for weekday in day_ints:
                for hour, minute in time_tuples:
                    entries.append({"Weekday": weekday, "Hour": hour, "Minute": minute})
        else:
            for hour, minute in time_tuples:
                entries.append({"Hour": hour, "Minute": minute})

        keys["StartCalendarInterval"] = entries[0] if len(entries) == 1 else entries
        return keys

    raise JobSpecError(f"unknown schedule kind {kind!r}")


def normalize_days(value):
    """Validate weekday names (comma-string or list) -> sorted-unique lowercase names."""
    tokens = value.split(",") if isinstance(value, str) else list(value)
    found = {}
    for token in tokens:
        name = token.strip().lower()
        if not name:
            continue
        if name not in _WEEKDAYS:
            raise JobSpecError(
                f"unknown day {token.strip()!r}; use {', '.join(_WEEKDAYS)}"
            )
        found[name] = _WEEKDAYS[name]
    if not found:
        raise JobSpecError(f"no valid days in {value!r}")
    return [name for name, _ in sorted(found.items(), key=lambda kv: kv[1])]


def parse_at_token(token):
    """'HH:MM' -> (None, 'HH:MM'); 'mon,fri 18:00' -> (['mon','fri'], '18:00')."""
    parts = token.strip().split(None, 1)
    if len(parts) == 2:
        days_part, time_part = parts
        hour, minute = parse_time(time_part)
        return normalize_days(days_part), f"{hour:02d}:{minute:02d}"
    hour, minute = parse_time(token)
    return None, f"{hour:02d}:{minute:02d}"


def build_calendar_schedule(at_tokens, days=None, run_at_load=False):
    """Assemble a calendar schedule manifest from --at tokens and optional --days.

    Weekdays may come from --days OR be embedded in every --at token, but not
    both, and embedded weekdays must agree across tokens.
    """
    if not at_tokens:
        raise JobSpecError("need at least one --at time")
    parsed = [parse_at_token(token) for token in at_tokens]

    times = []
    for _, time_str in parsed:
        if time_str not in times:
            times.append(time_str)

    embedded = [day_list for day_list, _ in parsed if day_list is not None]
    if embedded:
        if days is not None:
            raise JobSpecError("set weekdays via --days OR inside --at, not both")
        if len(embedded) != len(parsed):
            raise JobSpecError("either every --at carries weekdays or none do (use --days)")
        first = embedded[0]
        if any(other != first for other in embedded[1:]):
            raise JobSpecError("weekdays must match across all --at; use --days instead")
        day_names = first
    else:
        day_names = normalize_days(days) if days else []

    return {
        "kind": "calendar",
        "times": times,
        "days": day_names,
        "run_at_load": bool(run_at_load),
    }


def build_interval_schedule(every, run_at_load=False):
    """Assemble an interval schedule manifest; validates the interval string."""
    parse_every(every)  # validate; raises JobSpecError if bad
    return {
        "kind": "interval",
        "every": every.strip().lower(),
        "run_at_load": bool(run_at_load),
    }


def human_schedule(schedule):
    """One-line human summary of a schedule, for list/show output."""
    if schedule.get("kind") == "interval":
        summary = f"every {schedule['every']}"
    else:
        times = ", ".join(schedule.get("times") or [])
        days = schedule.get("days") or []
        when = ",".join(days) if days else "daily"
        summary = f"{when} at {times}"
    if schedule.get("run_at_load"):
        summary += " (+at load)"
    return summary


def build_label(name):
    """Reverse-DNS launchd label for a job name."""
    return f"{LABEL_PREFIX}.{name}"


def job_paths(jobs_dir, name):
    """Compute all on-disk paths for a job (no filesystem access)."""
    base = Path(jobs_dir) / name
    return JobPaths(
        dir=base,
        toml=base / "job.toml",
        wrapper=base / "wrapper.sh",
        plist=base / f"{build_label(name)}.plist",
        log_out=base / "logs" / "out.log",
        log_err=base / "logs" / "err.log",
    )


def render_wrapper(working_dir, command):
    """The per-job wrapper.sh. Generated once, then owned by the user.

    Not `exec`-ed so we can log the exit code for troubleshooting. `set -e`
    is deliberately omitted so a non-zero command exit still gets logged.
    """
    return f"""#!/bin/zsh
# generated by pj — rebuilt from job.toml on `pj apply`. Delete THIS marker
# line to adopt the file (pj then leaves it alone; --regen-wrapper rebuilds).
# Sourced into your interactive zsh, so PATH, aliases and functions all apply.
set -o pipefail
echo "=== pj run: $(date -Iseconds) ==="
cd {shlex.quote(working_dir)} || {{ echo "pj: cannot cd to {working_dir}" >&2; exit 1; }}
{command}
rc=$?
echo "=== pj done (exit $rc): $(date -Iseconds) ==="
exit $rc
"""


def render_plist(label, wrapper_path, schedule_keys, log_out, log_err):
    """Full launchd plist XML. `zsh -i` loads the user's interactive env, then
    sources the wrapper into it — so aliases and functions apply too, not just
    exported PATH/vars (which a fresh exec'd shell would be limited to)."""
    data = {
        "Label": label,
        "ProgramArguments": [
            "/bin/zsh",
            "-i",
            "-c",
            f"source {shlex.quote(str(wrapper_path))}",
        ],
        "StandardOutPath": str(log_out),
        "StandardErrorPath": str(log_err),
        "ProcessType": "Background",
    }
    data.update(schedule_keys)
    xml = plistlib.dumps(data).decode()
    return xml.replace(
        '<plist version="1.0">\n',
        f'<plist version="1.0">\n{_PLIST_COMMENT}\n',
        1,
    )


def _toml_str(value):
    out = (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\t", "\\t")
        .replace("\r", "\\r")
    )
    return f'"{out}"'


def _toml_value(value):
    if isinstance(value, bool):  # must precede int — bool is an int subclass
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, str):
        return _toml_str(value)
    if isinstance(value, list):
        return "[" + ", ".join(_toml_value(item) for item in value) + "]"
    raise TypeError(f"unsupported TOML value: {value!r}")


def dump_toml(data):
    """Minimal TOML emitter for our flat manifest schema (scalars, str lists,
    one level of [tables]). Read back with load_toml/tomllib."""
    scalar_lines, table_lines = [], []
    for key, value in data.items():
        if isinstance(value, dict):
            table_lines.append("")
            table_lines.append(f"[{key}]")
            for sub_key, sub_value in value.items():
                table_lines.append(f"{sub_key} = {_toml_value(sub_value)}")
        else:
            scalar_lines.append(f"{key} = {_toml_value(value)}")
    return "\n".join(scalar_lines + table_lines) + "\n"


def load_toml(text):
    """Parse a job.toml back into a dict (robust, stdlib)."""
    return tomllib.loads(text)
